name: GitHub Metrics Update

on:
  schedule:
    # Update metrics every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:


  

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          user: vibhanshu054
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, notable
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-metrics.svg
          if git diff --quiet --cached; then
            echo "No changes to commit"
          else
            git commit -m "chore: update github metrics"
            git push
          fi
